name: Codacy Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 13 * * 1'  # 每周一 13:15 UTC 运行

permissions:
  contents: read

jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read  # 允许 actions/checkout 获取代码
      security-events: write  # 允许 github/codeql-action/upload-sarif 上传 SARIF 结果
      actions: read  # 仅在私有仓库中需要

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set UTF-8 Environment Variables
        run: |
          echo "Setting environment variables for UTF-8"
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8

      - name: Validate File Encoding
        run: |
          echo "Checking for non-UTF-8 files..."
          find . -type f -exec file --mime {} + | grep -v 'charset=utf-8' || echo "All files are UTF-8"

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@d840f886c4bd4edc059706d09c6a1586111c540b
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
