name: Ensure Docker 2375 is Open and Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.24-dind
        options: --privileged
        ports:
          - 2375:2375
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Wait for Docker Daemon to be Ready
      run: |
        echo "Waiting for Docker to start..."
        sleep 15  # 确保 Docker 完全启动
        docker info  # 确保 Docker 运行正常

    - name: Check if 2375 is open
      run: |
        sudo netstat -tlnp | grep 2375 || echo "2375 is not open!"

    - name: Build with Maven
      env:
        DOCKER_HOST: "tcp://127.0.0.1:2375"
      run: mvn -B package --file pom.xml
