name: Build and Push Docker Image on GitHub Actions
on:
  pull_request:
  push:
    branches: 
      - master
jobs:
  build_container:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Test Connection
        run: |
          apt-get update
          apt-get install -y iputils-ping
          ping -c 3 docker

      - name: Verify Docker
        run: |
          docker version
          docker info

      - name: Build Docker Image
        run: |
          echo -e "FROM ubuntu:latest\nRUN echo 'Hello from Docker!' > /hello.txt" > Dockerfile
          docker build -t my-simple-image .

      - name: Run Docker Container and Check Output
        run: |
          docker run --rm my-simple-image cat /hello.txt

      - name: List Docker Images
        run: |
          docker images
