name: Build Maven Project and Docker Image on GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_maven_and_docker:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable-dind
        options: --privileged
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install socat
        run: |
          sudo apt-get update
          sudo apt-get install -y socat maven

      - name: Forward TCP 2375 to Docker's Unix socket
        run: |
          socat TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock &

      - name: Set up Docker Host
        run: |
          echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV

      - name: Wait for Docker to start
        run: |
          for i in {1..30}; do
            if docker -H tcp://localhost:2375 info > /dev/null 2>&1; then
              echo "Docker is ready!"
              break
            else
              echo "Waiting for Docker to start... Attempt $i"
              sleep 5
            fi
          done

      - name: Build Maven Project
        run: |
          mvn clean install -DskipTests

      - name: Build Docker Image from Dockerfile
        run: |
          echo -e "FROM openjdk:11-jre-slim\nCOPY target/*.jar app.jar\nENTRYPOINT [\"java\", \"-jar\", \"/app.jar\"]" > Dockerfile
          docker -H tcp://localhost:2375 build -t my-maven-app .

      - name: Run Docker Container and Check Output
        run: |
          docker -H tcp://localhost:2375 run --rm my-maven-app

      - name: List Docker Images
        run: |
          docker -H tcp://localhost:2375 images
