name: Build and Push Docker Image on GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_container:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable-dind
        options: --privileged -p 2375:2375
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Wait for Docker to start
        run: |
          # 等待 Docker 启动
          sleep 15

      - name: Test Docker Connection
        run: |
          docker -H tcp://localhost:2375 info

      - name: Build Docker Image
        run: |
          echo -e "FROM ubuntu:latest\nRUN echo 'Hello from Docker!' > /hello.txt" > Dockerfile
          docker -H tcp://localhost:2375 build -t my-simple-image .

      - name: Run Docker Container and Check Output
        run: |
          docker -H tcp://localhost:2375 run --rm my-simple-image cat /hello.txt

      - name: List Docker Images
        run: |
          docker -H tcp://localhost:2375 images
