name: Build Docker Image on GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_container:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable-dind
        options: --privileged -p 2375:2375
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Host
        run: |
          # 设置 Docker 主机环境变量为全局变量
          echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV

      - name: Wait for Docker to start
        run: |
          # 等待 Docker 启动并轮询直到 Docker 服务准备好
          for i in {1..30}; do
            if docker -H tcp://localhost:2375 info > /dev/null 2>&1; then
              echo "Docker is ready!"
              break
            else
              echo "Waiting for Docker to start... Attempt $i"
              sleep 5
            fi
          done

      - name: Build Docker Image
        run: |
          echo -e "FROM ubuntu:latest\nRUN echo 'Hello from Docker!' > /hello.txt" > Dockerfile
          docker -H tcp://localhost:2375 build -t my-simple-image .

      - name: Run Docker Container and Check Output
        run: |
          docker -H tcp://localhost:2375 run --rm my-simple-image cat /hello.txt

      - name: List Docker Images
        run: |
          docker -H tcp://localhost:2375 images
