name: Build Docker Image on GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_container:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable-dind
        options: --privileged
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install socat
        run: |
          sudo apt-get update
          sudo apt-get install -y socat

      - name: Forward TCP 2375 to Docker's Unix socket
        run: |
          # 使用 socat 将 2375 端口转发到 Docker 本地 Unix socket
          socat TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock &
        
      - name: Set up Docker Host
        run: |
          # 设置 Docker 主机环境变量为全局变量
          echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV

      - name: Wait for Docker to start
        run: |
          # 等待 Docker 启动并轮询直到 Docker 服务准备好
          for i in {1..30}; do
            if docker -H tcp://localhost:2375 info > /dev/null 2>&1; then
              echo "Docker is ready!"
              break
            else
              echo "Waiting for Docker to start... Attempt $i"
              sleep 5
            fi
          done

      - name: Build Docker Image
        run: |
          echo -e "FROM ubuntu:latest\nRUN echo 'Hello from Docker!' > /hello.txt" > Dockerfile
          docker -H tcp://localhost:237
